### ISSUE TITLE
vector-pop-position does not pop last vector element

### ISSUE THREAD

**Issue by khirbat** [Shinmera/array-utils#1]
```
CL-USER> (let ((x (make-array 4
                              :adjustable t
                              :fill-pointer t
                              :initial-contents #(0 1 2 3))))
           (values (array-utils:vector-pop-position x 3) x (fill-pointer x)))
```
```
3
#(0 1 2 3)
4
```
6d91e3131b35008f864eec5cc7e35e8c8aeaac7a works as expected
```
3
#(0 1 2)
3
```

I encountered this when some of my `(lquery:$ "..." (remove))` constructs stopped working after I upgraded to the August Quicklisp dist.

**Comment by Shinmera** [comment]
Gah. And here I thought I had written tests for all the cases. Sorry about that.

**Comment by Shinmera** [comment]
Alright, should be fixed now. Thanks for reporting it to me!

**Comment by khirbat** [comment]
Thanks for taking care of this so quickly! My `(lquery:$ "..." (remove))` code looks good too.
