### ISSUE TITLE
ensure-array-size should pass initial-element ro adjust-array

### ISSUE THREAD

**Issue by Yehouda** [Shinmera/array-utils#4]
**ensure-array-size** calls **ensure-array-size**, potentially enlarging it. The entry for **adjust-array** http://www.lispworks.com/documentation/HyperSpec/Body/f_adjust.htm says:

> The elements of the resulting array that are not in the bounds of array are initialized to initial-element; if initial-element is not provided, the consequences of later reading any such new element of new-array before it has been initialized are undefined. 

That means elemnts in the enlarged array undefined (looks to me like a bug in the standard, should initialize it to nil like **make-array** does).  

Some of the tests fail unless the new elements are 0.

**Comment by Shinmera** [comment]
Unless initial-element is specified, make-array does not initialize to NIL either.
